feat: Delete http errors from service
pagopa/idpay-iban pull request #122
Opened 2023-12-12 15:27 UTC by LarissaASLeite

#### Description

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

- Pre-Deploy Test
    - [ ] Unit
    - [ ] Integration (Narrow)
- Post-Deploy Test
    - [ ] Isolated Microservice
    - [ ] Broader Integration
    - [ ] Acceptance
    - [ ] Performance & Load

#### Types of changes

- [ ] PATCH - Bug fix (backwards compatible bug fixes)
- [ ] MINOR - New feature (add functionality in a backwards compatible manner)
- [ ] MAJOR - Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-12-13 16:02 UTC, stedelia approved these changes

2023-12-19 16:15 UTC, antonioT90 requested changes

2023-12-19 16:15 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/common/web/exception/ValidationExceptionHandler.java
> +    return new ErrorDTO(IbanConstants.ExceptionCode.INVALID_REQUEST, message);
this is a "common" class! remove the dependency from the "iban" class: eg we could define a @Bean templateValidationErrorDTO used just to provide default configuration in order to set here the "code"

2023-12-20 09:57 UTC, antonioT90 requested changes

2023-12-20 09:57 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/common/web/exception/ValidationExceptionHandler.java
> +                .orElse(new ErrorDTO("INVALID_REQUESTS", "Invalid requests"));
```suggestion
                .orElse(new ErrorDTO("INVALID_REQUEST", "Invalid request"));
```

2023-12-22 08:45 UTC, GiovanaSolorzano commented
Pending approval from IO

2024-01-12 11:53 UTC, merged